
no_index: 
  directory: 
    - inc
    - t
generated_by: Module::Install version 0.62
distribution_type: module
version: 0.02
name: YAML-Tiny
author: Adam Kennedy <cpan@ali.as>
license: perl
build_requires: 
  Test::More: 0.47
requires: 
  perl: 5.004
abstract: Read/Write YAML files with as little code as possible
