--- #YAML:1.0
name:                YAML-Tiny
version:             1.17
abstract:            Read/Write YAML files with as little code as possible
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
    File::Spec:                    0.80
    perl:                          5.004
    Test::More:                    0.47
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Adam Kennedy <adamk@cpan.org>
