
no_index: 
  directory: 
    - inc
    - t
generated_by: Module::Install version 0.64
distribution_type: module
version: 0.11
name: YAML-Tiny
author: Adam Kennedy <cpan@ali.as>
license: perl
build_requires: 
  Test::More: 0.47
  File::Spec: 0.80
requires: 
  perl: 5.005
abstract: Read/Write YAML files with as little code as possible
