abstract: Read/Write YAML files with as little code as possible
author: Adam Kennedy <adamk@cpan.org>
build_requires: 
  File::Spec: 0.80
  Test::More: 0.47
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: YAML-Tiny
no_index: 
  directory: 
    - inc
    - t
requires: 
  perl: 5.005
version: 1.02
